require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InsiderDataController do

  # This should return the minimal set of attributes required to create a valid
  # InsiderDatum. As you add validations to InsiderDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InsiderDataController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all insider_data as @insider_data" do
      insider_datum = InsiderDatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:insider_data).should eq([insider_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested insider_datum as @insider_datum" do
      insider_datum = InsiderDatum.create! valid_attributes
      get :show, {:id => insider_datum.to_param}, valid_session
      assigns(:insider_datum).should eq(insider_datum)
    end
  end

  describe "GET new" do
    it "assigns a new insider_datum as @insider_datum" do
      get :new, {}, valid_session
      assigns(:insider_datum).should be_a_new(InsiderDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested insider_datum as @insider_datum" do
      insider_datum = InsiderDatum.create! valid_attributes
      get :edit, {:id => insider_datum.to_param}, valid_session
      assigns(:insider_datum).should eq(insider_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InsiderDatum" do
        expect {
          post :create, {:insider_datum => valid_attributes}, valid_session
        }.to change(InsiderDatum, :count).by(1)
      end

      it "assigns a newly created insider_datum as @insider_datum" do
        post :create, {:insider_datum => valid_attributes}, valid_session
        assigns(:insider_datum).should be_a(InsiderDatum)
        assigns(:insider_datum).should be_persisted
      end

      it "redirects to the created insider_datum" do
        post :create, {:insider_datum => valid_attributes}, valid_session
        response.should redirect_to(InsiderDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved insider_datum as @insider_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        InsiderDatum.any_instance.stub(:save).and_return(false)
        post :create, {:insider_datum => {}}, valid_session
        assigns(:insider_datum).should be_a_new(InsiderDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InsiderDatum.any_instance.stub(:save).and_return(false)
        post :create, {:insider_datum => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested insider_datum" do
        insider_datum = InsiderDatum.create! valid_attributes
        # Assuming there are no other insider_data in the database, this
        # specifies that the InsiderDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InsiderDatum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => insider_datum.to_param, :insider_datum => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested insider_datum as @insider_datum" do
        insider_datum = InsiderDatum.create! valid_attributes
        put :update, {:id => insider_datum.to_param, :insider_datum => valid_attributes}, valid_session
        assigns(:insider_datum).should eq(insider_datum)
      end

      it "redirects to the insider_datum" do
        insider_datum = InsiderDatum.create! valid_attributes
        put :update, {:id => insider_datum.to_param, :insider_datum => valid_attributes}, valid_session
        response.should redirect_to(insider_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the insider_datum as @insider_datum" do
        insider_datum = InsiderDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InsiderDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => insider_datum.to_param, :insider_datum => {}}, valid_session
        assigns(:insider_datum).should eq(insider_datum)
      end

      it "re-renders the 'edit' template" do
        insider_datum = InsiderDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InsiderDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => insider_datum.to_param, :insider_datum => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested insider_datum" do
      insider_datum = InsiderDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => insider_datum.to_param}, valid_session
      }.to change(InsiderDatum, :count).by(-1)
    end

    it "redirects to the insider_data list" do
      insider_datum = InsiderDatum.create! valid_attributes
      delete :destroy, {:id => insider_datum.to_param}, valid_session
      response.should redirect_to(insider_data_url)
    end
  end

end
