require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NonPlayerCharactersController do

  # This should return the minimal set of attributes required to create a valid
  # NonPlayerCharacter. As you add validations to NonPlayerCharacter, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {size: "medium"}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NonPlayerCharactersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET show" do
    it "assigns the requested non_player_character as @non_player_character" do
      non_player_character = NonPlayerCharacter.create! valid_attributes
      get :show, {:id => non_player_character.to_param}, valid_session
      assigns(:non_player_character).should eq(non_player_character)
    end
  end

  describe "GET new" do
    it "assigns a new non_player_character as @non_player_character" do
      get :new, {}, valid_session
      assigns(:non_player_character).should be_a_new(NonPlayerCharacter)
    end
  end

  describe "GET edit" do
    it "assigns the requested non_player_character as @non_player_character" do
      non_player_character = NonPlayerCharacter.create! valid_attributes
      get :edit, {:id => non_player_character.to_param}, valid_session
      assigns(:non_player_character).should eq(non_player_character)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NonPlayerCharacter" do
        expect {
          post :create, {:non_player_character => valid_attributes}, valid_session
        }.to change(NonPlayerCharacter, :count).by(1)
      end

      it "assigns a newly created non_player_character as @non_player_character" do
        post :create, {:non_player_character => valid_attributes}, valid_session
        assigns(:non_player_character).should be_a(NonPlayerCharacter)
        assigns(:non_player_character).should be_persisted
      end

      it "redirects to the created non_player_character" do
        post :create, {:non_player_character => valid_attributes}, valid_session
        response.should redirect_to(NonPlayerCharacter.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved non_player_character as @non_player_character" do
        # Trigger the behavior that occurs when invalid params are submitted
        NonPlayerCharacter.any_instance.stub(:save).and_return(false)
        post :create, {:non_player_character => {}}, valid_session
        assigns(:non_player_character).should be_a_new(NonPlayerCharacter)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NonPlayerCharacter.any_instance.stub(:save).and_return(false)
        post :create, {:non_player_character => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested non_player_character" do
        non_player_character = NonPlayerCharacter.create! valid_attributes
        # Assuming there are no other non_player_characters in the database, this
        # specifies that the NonPlayerCharacter created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NonPlayerCharacter.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => non_player_character.to_param, :non_player_character => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested non_player_character as @non_player_character" do
        non_player_character = NonPlayerCharacter.create! valid_attributes
        put :update, {:id => non_player_character.to_param, :non_player_character => valid_attributes}, valid_session
        assigns(:non_player_character).should eq(non_player_character)
      end

      it "redirects to the non_player_character" do
        non_player_character = NonPlayerCharacter.create! valid_attributes
        put :update, {:id => non_player_character.to_param, :non_player_character => valid_attributes}, valid_session
        response.should redirect_to(non_player_character)
      end
    end

    describe "with invalid params" do
      it "assigns the non_player_character as @non_player_character" do
        non_player_character = NonPlayerCharacter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NonPlayerCharacter.any_instance.stub(:save).and_return(false)
        put :update, {:id => non_player_character.to_param, :non_player_character => {}}, valid_session
        assigns(:non_player_character).should eq(non_player_character)
      end

      it "re-renders the 'edit' template" do
        non_player_character = NonPlayerCharacter.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NonPlayerCharacter.any_instance.stub(:save).and_return(false)
        put :update, {:id => non_player_character.to_param, :non_player_character => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

end
